-- ============================================================
-- DQ_INVALID_NPI_TREND
-- Monthly trend of invalid NPIs in Medicaid claims
-- ============================================================

USE DATABASE ANALYTICS_MEDICAID;
USE SCHEMA MODEL;

CREATE OR REPLACE TABLE DQ_INVALID_NPI_TREND AS
WITH invalid_billing AS (
    SELECT f.CLAIM_MONTH, COUNT(*) AS INVALID_BILLING_COUNT
    FROM MODEL.FACT_MEDICAID_PROVIDER_SPENDING f
    LEFT JOIN MODEL.PROVIDER_DIM p ON f.BILLING_PROVIDER_NPI = p.NPI
    WHERE (p.NPI IS NULL OR p.DATA_QUALITY_FLAG = 'INVALID_NPI')
      AND f.BILLING_PROVIDER_NPI IS NOT NULL
    GROUP BY f.CLAIM_MONTH
),
invalid_servicing AS (
    SELECT f.CLAIM_MONTH, COUNT(*) AS INVALID_SERVICING_COUNT
    FROM MODEL.FACT_MEDICAID_PROVIDER_SPENDING f
    LEFT JOIN MODEL.PROVIDER_DIM p ON f.SERVICING_PROVIDER_NPI = p.NPI
    LEFT JOIN MODEL.LEGACY_SERVICING_PROVIDER_DIM l ON f.SERVICING_PROVIDER_NPI = l.LEGACY_ID
    WHERE (
            (p.NPI IS NULL AND l.LEGACY_ID IS NULL)
            OR p.DATA_QUALITY_FLAG = 'INVALID_NPI'
          )
      AND f.SERVICING_PROVIDER_NPI IS NOT NULL
    GROUP BY f.CLAIM_MONTH
),
claim_months AS (
    SELECT DISTINCT CLAIM_MONTH
    FROM MODEL.FACT_MEDICAID_PROVIDER_SPENDING
)
SELECT
    m.CLAIM_MONTH,
    COALESCE(b.INVALID_BILLING_COUNT, 0) AS INVALID_BILLING_COUNT,
    COALESCE(s.INVALID_SERVICING_COUNT, 0) AS INVALID_SERVICING_COUNT,
    COALESCE(b.INVALID_BILLING_COUNT, 0) + COALESCE(s.INVALID_SERVICING_COUNT, 0) AS TOTAL_INVALID_NPI
FROM claim_months m
LEFT JOIN invalid_billing b ON m.CLAIM_MONTH = b.CLAIM_MONTH
LEFT JOIN invalid_servicing s ON m.CLAIM_MONTH = s.CLAIM_MONTH
ORDER BY m.CLAIM_MONTH;
