-- DQ Anomaly Detector (SQL + Documentation) dq_invalid_npi_anomalies.sql


CREATE OR REPLACE TABLE MODEL.DQ_INVALID_NPI_ANOMALIES AS
WITH trend AS (
    SELECT
        CLAIM_MONTH,
        COUNT(*) AS INVALID_CLAIMS
    FROM MODEL.FACT_MEDICAID_PROVIDER_SPENDING f
    LEFT JOIN MODEL.PROVIDER_DIM p
        ON f.SERVICING_PROVIDER_NPI = p.NPI
    WHERE p.DATA_QUALITY_FLAG = 'INVALID_NPI'
    GROUP BY CLAIM_MONTH
),
stats AS (
    SELECT
        AVG(INVALID_CLAIMS) AS AVG_CLAIMS,
        STDDEV(INVALID_CLAIMS) AS STD_CLAIMS
    FROM trend
)
SELECT
    t.CLAIM_MONTH,
    t.INVALID_CLAIMS,
    CASE 
        WHEN t.INVALID_CLAIMS > s.AVG_CLAIMS + 3 * s.STD_CLAIMS THEN 'SPIKE'
        WHEN t.INVALID_CLAIMS < s.AVG_CLAIMS - 3 * s.STD_CLAIMS THEN 'DROP'
        ELSE 'NORMAL'
    END AS ANOMALY_STATUS
FROM trend t CROSS JOIN stats s;
