-- legacy_servicing_provider_dim.sql

CREATE OR REPLACE TABLE MODEL.LEGACY_SERVICING_PROVIDER_DIM AS
WITH legacy_ids AS (
    SELECT DISTINCT
        SERVICING_PROVIDER_NPI AS LEGACY_ID
    FROM MODEL.FACT_MEDICAID_PROVIDER_SPENDING
    WHERE NOT REGEXP_LIKE(SERVICING_PROVIDER_NPI, '^[0-9]{10}$')
)
SELECT
    l.LEGACY_ID,
    CASE 
        WHEN LEGACY_ID LIKE 'A%' THEN 'Agency / Atypical Provider'
        WHEN LEGACY_ID LIKE 'M%' THEN 'Managed Care / County Provider'
        ELSE 'Other Legacy Identifier'
    END AS PROVIDER_CATEGORY,
    COUNT(f.TOTAL_CLAIM_LINES) AS CLAIM_VOLUME,
    ANY_VALUE(f.SERVICE_CATEGORY) AS SAMPLE_SERVICE_CATEGORY
FROM legacy_ids l
LEFT JOIN MODEL.FACT_MEDICAID_PROVIDER_SPENDING f
    ON f.SERVICING_PROVIDER_NPI = l.LEGACY_ID
GROUP BY l.LEGACY_ID;
