-- HCPCS Ingestion: RAW (wide) + CLEAN

USE DATABASE RAW_MEDICAID;
USE SCHEMA PUBLIC;

CREATE OR REPLACE FILE FORMAT MEDICAID_CSV_FORMAT
  TYPE = 'CSV'
  FIELD_DELIMITER = ','
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  NULL_IF = ('', 'NULL', 'null');

CREATE OR REPLACE TABLE HCPCS_RAW_WIDE (
    HCPC STRING,
    SEQNUM STRING,
    RECID STRING,
    LONG_DESCRIPTION STRING,
    SHORT_DESCRIPTION STRING,
    PRICE1 STRING,
    PRICE2 STRING,
    PRICE3 STRING,
    PRICE4 STRING,
    MULT_PI STRING,
    CIM1 STRING,
    CIM2 STRING,
    CIM3 STRING,
    MCM1 STRING,
    MCM2 STRING,
    MCM3 STRING,
    STATUTE STRING,
    LABCERT1 STRING,
    LABCERT2 STRING,
    LABCERT3 STRING,
    LABCERT4 STRING,
    LABCERT5 STRING,
    LABCERT6 STRING,
    LABCERT7 STRING,
    LABCERT8 STRING,
    XREF1 STRING,
    XREF2 STRING,
    XREF3 STRING,
    XREF4 STRING,
    XREF5 STRING,
    COV STRING,
    ASC_GRP STRING,
    ASC_DT STRING,
    OPPS STRING,
    OPPS_PI STRING,
    OPPS_DT STRING,
    PROCNOTE STRING,
    BETOS STRING,
    TOS1 STRING,
    TOS2 STRING,
    TOS3 STRING,
    TOS4 STRING,
    TOS5 STRING,
    ANEST_BU STRING,
    ADD_DT STRING,
    ACT_EFF_DT STRING,
    TERM_DT STRING,
    ACTION_CD STRING
);

-- Load the HCPCS CSV (or CSV.gz) from MEDICAID_EXTRACTED
COPY INTO HCPCS_RAW_WIDE
FROM @MEDICAID_EXTRACTED
FILE_FORMAT = (FORMAT_NAME = 'MEDICAID_CSV_FORMAT')
ON_ERROR = 'CONTINUE';

-- Row count validation
SELECT COUNT(*) AS RAW_ROW_COUNT FROM HCPCS_RAW_WIDE;