-- ============================================================
-- HCPCS DIMENSION TABLE (ANALYTICS LAYER)
-- Deduplicates by HCPCS_CODE using EFFECTIVE_DATE
-- ============================================================

USE DATABASE ANALYTICS_MEDICAID;
USE SCHEMA MODEL;

CREATE OR REPLACE TABLE HCPCS_DIM AS
SELECT
    HCPCS_CODE,
    DESCRIPTION,
    SHORT_DESCRIPTION,
    STATUS,
    EFFECTIVE_DATE,
    TERMINATION_DATE
FROM RAW_MEDICAID.PUBLIC.HCPCS_CLEAN
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY HCPCS_CODE
    ORDER BY EFFECTIVE_DATE DESC NULLS LAST
) = 1;

-- Dimension validation
SELECT COUNT(*) AS DIM_ROW_COUNT FROM HCPCS_DIM;
