-- Detect ALL rows with impossible TOTAL_PAID values (Anything over $100M per provider‑month is already suspicious)
SELECT
    BILLING_PROVIDER_NPI,
    SERVICING_PROVIDER_NPI,
    HCPCS_CODE,
    CLAIM_MONTH,
    TOTAL_PATIENTS,
    TOTAL_CLAIM_LINES,
    TOTAL_PAID
FROM STAGE_MEDICAID.CLEAN.MEDICAID_PROVIDER_SPENDING_STAGE
WHERE YEAR(CLAIM_MONTH) = 2018
  AND TOTAL_PAID > 100000000  -- > $100M
ORDER BY TOTAL_PAID DESC;

-- 2. Detect invalid NPIs (critical for column‑shift detection) - Real NPIs are 10 digits.
SELECT
    BILLING_PROVIDER_NPI,
    SERVICING_PROVIDER_NPI,
    COUNT(*) AS N_ROWS
FROM STAGE_MEDICAID.CLEAN.MEDICAID_PROVIDER_SPENDING_STAGE
WHERE YEAR(CLAIM_MONTH) = 2018
  AND (
        LENGTH(BILLING_PROVIDER_NPI) <> 10
     OR LENGTH(SERVICING_PROVIDER_NPI) <> 10
  )
GROUP BY 1,2
ORDER BY N_ROWS DESC;

-- 3. Detect NULL or invalid HCPCS codes - Column shifts often wipe out HCPCS.
SELECT
    BILLING_PROVIDER_NPI,
    SERVICING_PROVIDER_NPI,
    CLAIM_MONTH,
    TOTAL_PAID,
    HCPCS_CODE
FROM STAGE_MEDICAID.CLEAN.MEDICAID_PROVIDER_SPENDING_STAGE
WHERE YEAR(CLAIM_MONTH) = 2018
  AND (HCPCS_CODE IS NULL OR HCPCS_CODE = '')
ORDER BY TOTAL_PAID DESC;

-- ⭐ 4. Detect repeating‑pattern corruption - Your corrupted values contain repeating digits:333333, 444444, 555555, 666666

SELECT
    BILLING_PROVIDER_NPI,
    SERVICING_PROVIDER_NPI,
    CLAIM_MONTH,
    TOTAL_PAID
FROM STAGE_MEDICAID.CLEAN.MEDICAID_PROVIDER_SPENDING_STAGE
WHERE YEAR(CLAIM_MONTH) = 2018
  AND REGEXP_LIKE(TOTAL_PAID::STRING, '(333333|444444|555555|666666)')
ORDER BY TOTAL_PAID DESC;

-- 5. Detect column‑shift signatures - This query finds rows where TOTAL_PAID is huge but other fields look normal, This isolates misaligned rows.
SELECT
    BILLING_PROVIDER_NPI,
    SERVICING_PROVIDER_NPI,
    HCPCS_CODE,
    CLAIM_MONTH,
    TOTAL_PATIENTS,
    TOTAL_CLAIM_LINES,
    TOTAL_PAID
FROM STAGE_MEDICAID.CLEAN.MEDICAID_PROVIDER_SPENDING_STAGE
WHERE YEAR(CLAIM_MONTH) = 2018
  AND TOTAL_PAID > 1000000000  -- > $1B
  AND TOTAL_CLAIM_LINES BETWEEN 1 AND 20000
  AND TOTAL_PATIENTS BETWEEN 1 AND 20000
ORDER BY TOTAL_PAID DESC;

-- 6. Detect providers with ANY suspicious activity - It list of all providers with anomalies, their worst values, how many rows are affected
SELECT
    BILLING_PROVIDER_NPI,
    COUNT(*) AS N_ROWS,
    MAX(TOTAL_PAID) AS MAX_PAID,
    MIN(TOTAL_PAID) AS MIN_PAID,
    AVG(TOTAL_PAID) AS AVG_PAID
FROM STAGE_MEDICAID.CLEAN.MEDICAID_PROVIDER_SPENDING_STAGE
WHERE YEAR(CLAIM_MONTH) = 2018
GROUP BY BILLING_PROVIDER_NPI
HAVING MAX(TOTAL_PAID) > 100000000  -- > $100M
ORDER BY MAX_PAID DESC;

-- 7. Detect SERVICING_PROVIDER_NPI corruption, i.e NPI = 20
SELECT
    SERVICING_PROVIDER_NPI,
    COUNT(*) AS N_ROWS
FROM STAGE_MEDICAID.CLEAN.MEDICAID_PROVIDER_SPENDING_STAGE
WHERE YEAR(CLAIM_MONTH) = 2018
  AND LENGTH(SERVICING_PROVIDER_NPI) < 10
GROUP BY 1
ORDER BY N_ROWS DESC;

-- 8. Detect rows where TOTAL_PAID is not numeric. Column shifts often produce non‑numeric values that get coerced into huge numbers.
SELECT *
FROM STAGE_MEDICAID.CLEAN.MEDICAID_PROVIDER_SPENDING_STAGE
WHERE YEAR(CLAIM_MONTH) = 2018
  AND TRY_TO_NUMBER(TOTAL_PAID) IS NULL;

-- 9. Detect rows where TOTAL_PAID is a timestamp or ID
SELECT *
FROM STAGE_MEDICAID.CLEAN.MEDICAID_PROVIDER_SPENDING_STAGE
WHERE YEAR(CLAIM_MONTH) = 2018
  AND TOTAL_PAID > 1000000000000;  -- > $1T

-- 10. check for the actual HEX code
SELECT
    BILLING_PROVIDER_NPI,
    LENGTH(BILLING_PROVIDER_NPI) AS LEN_BILLING,
    HEX_ENCODE(BILLING_PROVIDER_NPI) AS BILLING_HEX,
    SERVICING_PROVIDER_NPI,
    LENGTH(SERVICING_PROVIDER_NPI) AS LEN_SERVICING,
    HEX_ENCODE(SERVICING_PROVIDER_NPI) AS SERVICING_HEX,
    HCPCS_CODE,
    TOTAL_PAID
FROM STAGE_MEDICAID.CLEAN.MEDICAID_PROVIDER_SPENDING_STAGE
WHERE TOTAL_PAID > 1000000000
ORDER BY TOTAL_PAID DESC;

-- check FACT_HCPCS_MONTHLY
SELECT
    HCPCS_CODE,
    CLAIM_MONTH,
    SUM(TOTAL_PAID) AS TOTAL_PAID
FROM ANALYTICS_MEDICAID.MODEL.FACT_HCPCS_MONTHLY
WHERE YEAR(CLAIM_MONTH) = 2018
GROUP BY 1,2
HAVING SUM(TOTAL_PAID) > 100000000  -- > $100M
ORDER BY TOTAL_PAID DESC;

SELECT *
FROM ANALYTICS_MEDICAID.MODEL.FACT_HCPCS_MONTHLY
WHERE YEAR(CLAIM_MONTH) = 2018
  AND TOTAL_PAID > 1000000000000;


