-- Remove corrupted rows from STAGE
DELETE FROM STAGE_MEDICAID.CLEAN.MEDICAID_PROVIDER_SPENDING_STAGE
WHERE TOTAL_PAID > 1000000000
  AND YEAR(CLAIM_MONTH) = 2018;


-- Remove them from FACT_MEDICAID_PROVIDER_SPENDING
DELETE FROM ANALYTICS_MEDICAID.MODEL.FACT_MEDICAID_PROVIDER_SPENDING
WHERE TOTAL_PAID > 100000000
  AND YEAR(CLAIM_MONTH) = 2018;


-- Validate
SELECT *
FROM STAGE_MEDICAID.CLEAN.MEDICAID_PROVIDER_SPENDING_STAGE
WHERE TOTAL_PAID > 1000000000
  AND YEAR(CLAIM_MONTH) = 2018;

-- Rebuild FACT_PROVIDER_MONTHLY for 2018
DELETE FROM ANALYTICS_MEDICAID.MODEL.FACT_PROVIDER_MONTHLY
WHERE YEAR(CLAIM_MONTH) = 2018;

INSERT INTO ANALYTICS_MEDICAID.MODEL.FACT_PROVIDER_MONTHLY
SELECT
    CLAIM_MONTH,
    BILLING_PROVIDER_NPI,
    BILLING_PROVIDER_STATE,
    SERVICING_PROVIDER_NPI,
    SERVICING_PROVIDER_STATE,
    SERVICE_CATEGORY,
    SUM(TOTAL_CLAIM_LINES),
    SUM(TOTAL_PAID),
    SUM(TOTAL_PATIENTS)
FROM ANALYTICS_MEDICAID.MODEL.FACT_MEDICAID_PROVIDER_SPENDING
WHERE YEAR(CLAIM_MONTH) = 2018
GROUP BY
    CLAIM_MONTH,
    BILLING_PROVIDER_NPI,
    BILLING_PROVIDER_STATE,
    SERVICING_PROVIDER_NPI,
    SERVICING_PROVIDER_STATE,
    SERVICE_CATEGORY;

-- Verify 2018 is clean
SELECT CLAIM_MONTH, SUM(TOTAL_PAID)
FROM ANALYTICS_MEDICAID.MODEL.FACT_PROVIDER_MONTHLY
WHERE YEAR(CLAIM_MONTH) = 2018
GROUP BY CLAIM_MONTH
ORDER BY CLAIM_MONTH;

-- Rebuild FACT_HCPCS_MONTHLY for 2018
DELETE FROM ANALYTICS_MEDICAID.MODEL.FACT_HCPCS_MONTHLY
WHERE YEAR(CLAIM_MONTH) = 2018
  AND TOTAL_PAID > 100000000;  -- > $100M;
  
INSERT INTO ANALYTICS_MEDICAID.MODEL.FACT_HCPCS_MONTHLY (
    BILLING_PROVIDER_NPI,
    BILLING_PROVIDER_STATE,
    CLAIM_MONTH,
    HCPCS_CODE,
    HCPCS_DESCRIPTION,
    HCPCS_SHORT_DESCRIPTION,
    HCPCS_STATUS,
    SERVICE_CATEGORY,
    SERVICING_PROVIDER_NPI,
    SERVICING_PROVIDER_STATE,
    TOTAL_CLAIM_LINES,
    TOTAL_PAID,
    TOTAL_PATIENTS
)
SELECT
    BILLING_PROVIDER_NPI,
    BILLING_PROVIDER_STATE,
    CLAIM_MONTH,
    HCPCS_CODE,
    HCPCS_DESCRIPTION,
    HCPCS_SHORT_DESCRIPTION,
    HCPCS_STATUS,
    SERVICE_CATEGORY,
    SERVICING_PROVIDER_NPI,
    SERVICING_PROVIDER_STATE,
    SUM(TOTAL_CLAIM_LINES) AS TOTAL_CLAIM_LINES,
    SUM(TOTAL_PAID) AS TOTAL_PAID,
    SUM(TOTAL_PATIENTS) AS TOTAL_PATIENTS
FROM ANALYTICS_MEDICAID.MODEL.FACT_MEDICAID_PROVIDER_SPENDING
WHERE YEAR(CLAIM_MONTH) = 2018
  AND HCPCS_CODE IS NOT NULL
GROUP BY
    BILLING_PROVIDER_NPI,
    BILLING_PROVIDER_STATE,
    CLAIM_MONTH,
    HCPCS_CODE,
    HCPCS_DESCRIPTION,
    HCPCS_SHORT_DESCRIPTION,
    HCPCS_STATUS,
    SERVICE_CATEGORY,
    SERVICING_PROVIDER_NPI,
    SERVICING_PROVIDER_STATE;

SELECT *
FROM ANALYTICS_MEDICAID.MODEL.FACT_HCPCS_MONTHLY
WHERE YEAR(CLAIM_MONTH) = 2018
  AND TOTAL_PAID > 100000000
ORDER BY TOTAL_PAID DESC;
