-- ============================================================
-- MEDICAID CLEAN TABLE (STAGE LAYER)
-- Standardizes types and prepares for analytics modeling
-- ============================================================

USE DATABASE STAGE_MEDICAID;
USE SCHEMA CLEAN;

CREATE OR REPLACE TABLE MEDICAID_PROVIDER_SPENDING_STAGE AS
SELECT
    LPAD(TRIM(BILLING_PROVIDER_NPI_NUM), 10, '0')   AS BILLING_PROVIDER_NPI,
    LPAD(TRIM(SERVICING_PROVIDER_NPI_NUM), 10, '0') AS SERVICING_PROVIDER_NPI,
    UPPER(TRIM(HCPCS_CODE))                         AS HCPCS_CODE,
    TRY_TO_DATE(CLAIM_FROM_MONTH || '-01')          AS CLAIM_MONTH,
    TRY_TO_NUMBER(TOTAL_PATIENTS)                   AS TOTAL_PATIENTS,
    TRY_TO_NUMBER(TOTAL_CLAIM_LINES)                AS TOTAL_CLAIM_LINES,
    TRY_TO_NUMBER(TOTAL_PAID)                       AS TOTAL_PAID
FROM RAW_MEDICAID.PUBLIC.MEDICAID_PROVIDER_SPENDING_RAW;

-- Validation
SELECT COUNT(*) AS STAGE_ROW_COUNT
FROM MEDICAID_PROVIDER_SPENDING_STAGE;
