-- ============================================================
-- MEDICAID FACT TABLE (ANALYTICS LAYER)
-- Enriched with HCPCS + Provider dimensions
-- SERVICE_CATEGORY: Derived field for ED/IP/OP/RX classification
-- Based on HCPCS patterns
-- ============================================================

USE DATABASE ANALYTICS_MEDICAID;
USE SCHEMA MODEL;

CREATE OR REPLACE TABLE FACT_MEDICAID_PROVIDER_SPENDING AS
SELECT
    s.BILLING_PROVIDER_NPI,
    s.SERVICING_PROVIDER_NPI,
    s.HCPCS_CODE,
    s.CLAIM_MONTH,
    s.TOTAL_PATIENTS,
    s.TOTAL_CLAIM_LINES,
    s.TOTAL_PAID,

    -- Derived service category (HCPCS-based)
    CASE
        WHEN s.HCPCS_CODE LIKE 'J%' THEN 'RX'
        WHEN s.HCPCS_CODE LIKE 'A0%' THEN 'OP'
        WHEN s.HCPCS_CODE LIKE 'G0%' THEN 'OP'
        WHEN s.HCPCS_CODE LIKE 'H0%' THEN 'OP'
        WHEN s.HCPCS_CODE LIKE 'T%' THEN 'OP'
        ELSE 'OTHER'
    END AS SERVICE_CATEGORY,

    -- Provider dimension joins
    p1.PRACTICE_STATE AS BILLING_PROVIDER_STATE,
    p2.PRACTICE_STATE AS SERVICING_PROVIDER_STATE,

    -- HCPCS dimension join
    h.DESCRIPTION AS HCPCS_DESCRIPTION,
    h.SHORT_DESCRIPTION AS HCPCS_SHORT_DESCRIPTION,
    h.STATUS AS HCPCS_STATUS

FROM STAGE_MEDICAID.CLEAN.MEDICAID_PROVIDER_SPENDING_STAGE s
LEFT JOIN ANALYTICS_MEDICAID.MODEL.NPI_DIM p1
    ON s.BILLING_PROVIDER_NPI = p1.NPI
LEFT JOIN ANALYTICS_MEDICAID.MODEL.NPI_DIM p2
    ON s.SERVICING_PROVIDER_NPI = p2.NPI
LEFT JOIN ANALYTICS_MEDICAID.MODEL.HCPCS_DIM h
    ON s.HCPCS_CODE = h.HCPCS_CODE;

-- Validation
SELECT COUNT(*) AS FACT_ROW_COUNT
FROM FACT_MEDICAID_PROVIDER_SPENDING;

-- VALIDATE SERVICE CATEGORIES
USE DATABASE ANALYTICS_MEDICAID;
USE SCHEMA MODEL;

SELECT SERVICE_CATEGORY, COUNT(*)
FROM FACT_MEDICAID_PROVIDER_SPENDING
GROUP BY SERVICE_CATEGORY
ORDER BY COUNT(*) DESC;

-- ============================================================
-- CLUSTERING: FACT_MEDICAID_PROVIDER_SPENDING
-- ============================================================
ALTER TABLE ANALYTICS_MEDICAID.MODEL.FACT_MEDICAID_PROVIDER_SPENDING
  CLUSTER BY (CLAIM_MONTH, BILLING_PROVIDER_NPI);

-- ============================================================
-- FOREIGN KEYS (DOCUMENTATION ONLY)
-- ============================================================

-- Billing provider → NPI_DIM
ALTER TABLE ANALYTICS_MEDICAID.MODEL.FACT_MEDICAID_PROVIDER_SPENDING
  ADD CONSTRAINT FK_FACT_BILLING_NPI
  FOREIGN KEY (BILLING_PROVIDER_NPI)
  REFERENCES ANALYTICS_MEDICAID.MODEL.NPI_DIM (NPI);

-- SERVICING provider → NPI_DIM
ALTER TABLE ANALYTICS_MEDICAID.MODEL.FACT_MEDICAID_PROVIDER_SPENDING
  ADD CONSTRAINT FK_FACT_RENDERING_NPI
  FOREIGN KEY (SERVICING_PROVIDER_NPI)
  REFERENCES ANALYTICS_MEDICAID.MODEL.NPI_DIM (NPI);

-- HCPCS → HCPCS_DIM
ALTER TABLE ANALYTICS_MEDICAID.MODEL.FACT_MEDICAID_PROVIDER_SPENDING
  ADD CONSTRAINT FK_FACT_HCPCS
  FOREIGN KEY (HCPCS_CODE)
  REFERENCES ANALYTICS_MEDICAID.MODEL.HCPCS_DIM (HCPCS_CODE);


