-- ============================================================
-- MEDICAID FACT TABLE (ANALYTICS LAYER)
-- Enriched with HCPCS + Provider dimensions
-- SERVICE_CATEGORY: Derived field for OP/RX/OTHER classification
-- ============================================================

USE DATABASE ANALYTICS_MEDICAID;
USE SCHEMA MODEL;

CREATE OR REPLACE TABLE FACT_MEDICAID_PROVIDER_SPENDING AS
SELECT
    s.BILLING_PROVIDER_NPI,
    s.SERVICING_PROVIDER_NPI,
    s.HCPCS_CODE,
    s.CLAIM_MONTH,
    s.TOTAL_PATIENTS,
    s.TOTAL_CLAIM_LINES,
    s.TOTAL_PAID,

    -- Derived service category (HCPCS-based)
    CASE
        WHEN s.HCPCS_CODE LIKE 'J%' THEN 'RX'
        WHEN s.HCPCS_CODE LIKE 'A0%' THEN 'OP'
        WHEN s.HCPCS_CODE LIKE 'G0%' THEN 'OP'
        WHEN s.HCPCS_CODE LIKE 'H0%' THEN 'OP'
        WHEN s.HCPCS_CODE LIKE 'T%' THEN 'OP'
        ELSE 'OTHER'
    END AS SERVICE_CATEGORY,

    -- Provider dimension joins (cleaned provider dimension)
    p1.PROVIDER_STATE_US       AS BILLING_PROVIDER_STATE,
    p1.PROVIDER_TYPE           AS BILLING_PROVIDER_TYPE,
    p1.PROVIDER_DISPLAY_NAME   AS BILLING_PROVIDER_NAME,

    p2.PROVIDER_STATE_US       AS SERVICING_PROVIDER_STATE,
    p2.PROVIDER_TYPE           AS SERVICING_PROVIDER_TYPE,
    p2.PROVIDER_DISPLAY_NAME   AS SERVICING_PROVIDER_NAME,

    -- HCPCS dimension join
    h.DESCRIPTION         AS HCPCS_DESCRIPTION,
    h.SHORT_DESCRIPTION   AS HCPCS_SHORT_DESCRIPTION,
    h.STATUS              AS HCPCS_STATUS

FROM STAGE_MEDICAID.CLEAN.MEDICAID_PROVIDER_SPENDING_STAGE s
LEFT JOIN ANALYTICS_MEDICAID.MODEL.PROVIDER_DIM p1
    ON s.BILLING_PROVIDER_NPI = p1.NPI
LEFT JOIN ANALYTICS_MEDICAID.MODEL.PROVIDER_DIM p2
    ON s.SERVICING_PROVIDER_NPI = p2.NPI
LEFT JOIN ANALYTICS_MEDICAID.MODEL.HCPCS_DIM h
    ON s.HCPCS_CODE = h.HCPCS_CODE;

-- ============================================================
-- VALIDATION
-- ============================================================

SELECT COUNT(*) AS FACT_ROW_COUNT
FROM FACT_MEDICAID_PROVIDER_SPENDING;

-- Validate service category distribution
SELECT SERVICE_CATEGORY, COUNT(*)
FROM FACT_MEDICAID_PROVIDER_SPENDING
GROUP BY SERVICE_CATEGORY
ORDER BY COUNT(*) DESC;

-- ============================================================
-- CLUSTERING: FACT_MEDICAID_PROVIDER_SPENDING
-- ============================================================

ALTER TABLE ANALYTICS_MEDICAID.MODEL.FACT_MEDICAID_PROVIDER_SPENDING
  CLUSTER BY (CLAIM_MONTH, BILLING_PROVIDER_NPI);

-- ============================================================
-- FOREIGN KEYS (DOCUMENTATION ONLY)
-- ============================================================

-- Billing provider → PROVIDER_DIM
ALTER TABLE ANALYTICS_MEDICAID.MODEL.FACT_MEDICAID_PROVIDER_SPENDING
  ADD CONSTRAINT FK_FACT_BILLING_PROVIDER
  FOREIGN KEY (BILLING_PROVIDER_NPI)
  REFERENCES ANALYTICS_MEDICAID.MODEL.PROVIDER_DIM (NPI);

-- Servicing provider → PROVIDER_DIM
ALTER TABLE ANALYTICS_MEDICAID.MODEL.FACT_MEDICAID_PROVIDER_SPENDING
  ADD CONSTRAINT FK_FACT_SERVICING_PROVIDER
  FOREIGN KEY (SERVICING_PROVIDER_NPI)
  REFERENCES ANALYTICS_MEDICAID.MODEL.PROVIDER_DIM (NPI);

-- HCPCS → HCPCS_DIM
ALTER TABLE ANALYTICS_MEDICAID.MODEL.FACT_MEDICAID_PROVIDER_SPENDING
  ADD CONSTRAINT FK_FACT_HCPCS
  FOREIGN KEY (HCPCS_CODE)
  REFERENCES ANALYTICS_MEDICAID.MODEL.HCPCS_DIM (HCPCS_CODE);
