-- ============================================================
-- MEDICAID QUALITY CHECKS
-- ============================================================

USE DATABASE STAGE_MEDICAID;
USE SCHEMA CLEAN;

-- Validate the RAW → CLEAN → FACT row counts are consistent
-- RAW Count — Validates Successful Ingestion
SELECT COUNT(*) FROM RAW_MEDICAID.PUBLIC.MEDICAID_PROVIDER_SPENDING_RAW;

-- No rows were lost during transformation...ideally RAW count == STAGE count
SELECT COUNT(*) FROM STAGE_MEDICAID.CLEAN.MEDICAID_PROVIDER_SPENDING_STAGE;

-- FACT Count — Validates Joins Didn’t Reduce the Dataset...ideally FACT count == STAGE count
SELECT COUNT(*) FROM ANALYTICS_MEDICAID.MODEL.FACT_PROVIDER_SPENDING;

-- Null NPI values
SELECT COUNT(*) AS NULL_NPI_ROWS
FROM MEDICAID_PROVIDER_SPENDING_STAGE
WHERE BILLING_PROVIDER_NPI IS NULL
   OR SERVICING_PROVIDER_NPI IS NULL;

-- Null HCPCS codes
SELECT COUNT(*) AS NULL_HCPCS_ROWS
FROM MEDICAID_PROVIDER_SPENDING_STAGE
WHERE HCPCS_CODE IS NULL;

-- Orphan HCPCS codes
SELECT DISTINCT HCPCS_CODE
FROM MEDICAID_PROVIDER_SPENDING_STAGE
WHERE HCPCS_CODE NOT IN (
    SELECT HCPCS_CODE FROM ANALYTICS_MEDICAID.MODEL.HCPCS_DIM
);

-- Orphan provider NPIs
SELECT DISTINCT BILLING_PROVIDER_NPI
FROM MEDICAID_PROVIDER_SPENDING_STAGE
WHERE BILLING_PROVIDER_NPI NOT IN (
    SELECT NPI FROM ANALYTICS_MEDICAID.MODEL.DIM_PROVIDER
);
